###############################
###       SYSTEM            ###
###############################

- alias: "Startup Notification"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: notify.ios_thorjan_x
      data:
        message: "Restarted"

###############################
###       LIGHTS            ###
###############################

- alias: 'Chili lys'
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.chili
    - delay: 14:00:00
    - service: switch.turn_off
      entity_id: switch.chili
- alias: 'Pia morgen'
  trigger:
    platform: time
    at: '06:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: light.turn_on
      data:
        entity_id: light.pia_under_bed
        brightness_pct: 50
        color_name: lime
        transition: 60
    - delay: 01:00:00
    - service: light.turn_off
      entity_id: light.pia_under_bed
- alias: 'Pia kveld'
  trigger:
    platform: time
    at: '18:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.pia_under_bed
        brightness_pct: 60
        color_name: hotpink
    - delay: 01:30:00
    - service: light.turn_off
      data:
        entity_id: light.pia_under_bed
        transition: 1800
- alias: 'Thorjan morgen'
  trigger:
    platform: time
    at: '08:30:00'
  action:
    - service: light.turn_off
      entity_id: light.master_thorjan
