###############################
###        SYSTEM           ###
###############################

- alias: "Startup Notification"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: !secret notification1
      data:
        message: "Restarted"

###############################
###        MORNING          ###
###############################

- alias: 'Morgenradio'
  trigger:
    platform: time
    at: '06:00:00'
  action:
    - service: media_player.volume_set
      data:
        entity_id: media_player.bad
        volume_level: .05
    - service: media_player.select_source
      data_template:
        entity_id:
          - media_player.bad
        source: 'NRK P13'
- alias: 'Pia morgen'
  trigger:
    platform: time
    at: '06:30:00'
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: light.turn_on
      data:
        entity_id: light.pia_under_bed
        brightness_pct: 50
        color_name: lime
        transition: 60
- alias: 'Chili lys'
  trigger:
    platform: time
    at: '07:00:00'
  action:
    - service: switch.turn_on
      entity_id: switch.chili
- alias: 'Morgen over'
  trigger:
    platform: time
    at: '08:30:00'
  action:
    - service: light.turn_off
      entity_id:
        - light.master_thorjan
        - light.pia_under_bed
    - service: media_player.media_pause
      entity_id: media_player.bad

###############################
###        EVENING          ###
###############################

- alias: 'Pia kveld'
  trigger:
    platform: time
    at: '18:00:00'
  action:
    - service: light.turn_on
      data:
        entity_id: light.pia_under_bed
        brightness_pct: 60
        color_name: hotpink
    - delay: 01:30:00
    - service: light.turn_off
      data:
        entity_id: light.pia_under_bed
        transition: 1800
- alias: 'Chili lys av'
  trigger:
    platform: time
    at: '21:00:00'
  action:
    - service: switch.turn_off
      entity_id: switch.chili

###############################
###        WEEKEND          ###
###############################

- alias: 'Helg'
  trigger:
    platform: time
    at: '20:00:00'
  condition:
    condition: time
    weekday:
      - fri
      - sat
  action:
    - service: switch.turn_on
      entity_id: switch.bookshelf

###############################
###         ZONES           ###
###############################

- alias: 'Tomt hus'
  trigger:
    platform: zone
    entity_id: group.all_devices
    zone: zone.home
    event: leave
  action:
    service: script.turn_on
    entity_id: script.no_one_home
- alias: 'Fra barnehage'
  trigger:
    platform: zone
    entity_id: !secret bhg_person
    zone: zone.barnehage
    event: leave
  condition:
    condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
  action:
    - service: !secret notification1
      data:
        message: "På vei hjem fra barnehagen"
