homeassistant:
  name: !secret name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 10
  unit_system: metric
  time_zone: !secret tz
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

influxdb: !include influx.yaml

discovery:
  ignore:
    #- apple_tv
    #- denonavr
    - harmony
    - philips_hue
    #- plex_mediaserver
    - samsung_tv
  #enable:
  #  - homekit

panel_iframe:
  influxdb:
    title: InfluxDB
    icon: mdi:database
    url: !secret influx_url
  grafana:
    title: Grafana
    icon: mdi:chart-line
    url: !secret grafana_url

sensor:
  - platform: yr
    monitored_conditions:
      - temperature
      - symbol
      - windSpeed
  - platform: darksky
    api_key: !secret dark_sky_token
    language: nb
    forecast:
      - 0
    monitored_conditions:
      - summary
  - platform: entur_public_transport
    stop_ids:
      - !secret buss1
      - !secret buss2
  - platform: systemmonitor
    resources:
      - type: disk_use_percent
        arg: /home
      - type: memory_free
      - type: processor_use
  - platform: uptime
  - platform: template
    sensors:
      entur_austbo_rute:
        friendly_name: "Rute"
        value_template: "{{ state_attr('sensor.entur_austbo_vest_platform_48514', 'route') }}"
        icon_template: mdi:bus
  - platform: template
    sensors:
      entur_ringnotveien_rute:
        friendly_name: "Rute"
        value_template: "{{ state_attr('sensor.entur_ringnotveien_platform_44778', 'route') }}"
        icon_template: mdi:bus
  - platform: template
    sensors:
      voltage_chili:
        friendly_name: "Spenning"
        unit_of_measurement: 'V'
        icon_template: mdi:flash
        value_template: "{{ state_attr('switch.chili', 'voltage') }}"
  - platform: rest
    resource: !secret hue_wc_temp
    value_template: '{{ value_json.state.temperature | float / 100 }}'
    unit_of_measurement: °C
    name: 'WC Temperature'
  - platform: rest
    resource: !secret hue_wc_lux
    value_template: '{{ value_json.state.lightlevel }}'
    unit_of_measurement: Lux
    name: 'WC Lux'
  - platform: pi_hole

air_quality:
  - platform: norway_air

weather:
  - platform: darksky
    api_key: !secret dark_sky_token

hue:
  bridges:
    - host: !secret hue_ip

media_player:
  - platform: samsungtv
    host: !secret samsungtv_ip
    mac: !secret samsungtv_mac
    port: 8001
  - platform: lg_netcast
    host: !secret lg_ip
    access_token: !secret lg_access_token

tibber:
  access_token: !secret tibber_token

# Light groups
light:
  - platform: group
    name: laundry
    entities:
      - light.laundry_ceiling3
      - light.laundry_ceiling4

switch:
  - platform: tplink
    host: !secret tplink_ip

# Text to speech
tts:
  - platform: google

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
