homeassistant:
  name: !secret name
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 10
  unit_system: metric
  time_zone: !secret tz
  customize: !include customize.yaml

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  base_url: !secret url
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

automation: !include automations.yaml
group: !include groups.yaml
influxdb: !include influx.yaml
script: !include scripts.yaml
sensor: !include sensors.yaml
zone: !include zones.yaml

discovery:
  ignore:
    #- apple_tv
    #- denonavr
    - harmony
    - philips_hue
    #- plex_mediaserver
    - samsung_tv
  #enable:
  #  - homekit

panel_iframe:
  influxdb:
    title: InfluxDB
    icon: mdi:database
    url: !secret influx_url
  grafana:
    title: Grafana
    icon: mdi:chart-line
    url: !secret grafana_url
  jupyterlab:
    title: JupyterLab
    icon: mdi:flask
    url: !secret jupyter_url

speedtestdotnet:
  scan_interval:
    minutes: 180
  monitored_conditions:
    - ping
    - download
    - upload

air_quality:
  - platform: norway_air

weather:
  - platform: darksky
    api_key: !secret dark_sky_token

hue:
  bridges:
    - host: !secret hue_ip

media_player:
  - platform: samsungtv
    host: !secret samsungtv_ip
    mac: !secret samsungtv_mac
    port: 8001
  - platform: lg_netcast
    host: !secret lg_ip
    access_token: !secret lg_access_token

tibber:
  access_token: !secret tibber_token

# Light groups
light:
  - platform: group
    name: laundry
    entities:
      - light.laundry_ceiling3
      - light.laundry_ceiling4

tplink:

homekit:
  filter:
    include_entities:
      switch.chili
  entity_config:
    switch.chili:
      name: Chili
      type: switch

# Text to speech
tts:
  - platform: google
