###############################
###        SYSTEM           ###
###############################

- platform: systemmonitor
  resources:
    - type: disk_use_percent
      arg: /home
    - type: memory_free
    - type: processor_use
- platform: uptime

###############################
###          BUS            ###
###############################

- platform: entur_public_transport
  stop_ids:
    - !secret buss1
    - !secret buss2
- platform: template
  sensors:
    entur_austbo_rute:
      friendly_name: "Rute"
      value_template: "{{ state_attr('sensor.entur_austbo_vest_platform_48514', 'route') }}"
      icon_template: mdi:bus
    entur_austbo_rute_next:
      friendly_name: "Rute"
      value_template: "{{ state_attr('sensor.entur_austbo_vest_platform_48514', 'next_route') }}"
      icon_template: mdi:bus
    entur_austbo_next:
      friendly_name: "Next Austbø"
      unit_of_measurement: min
      value_template: "{{ state_attr('sensor.entur_austbo_vest_platform_48514', 'next_due_in') }}"
      icon_template: mdi:clock-outline
    entur_ringnotveien_rute:
      friendly_name: "Rute"
      value_template: "{{ state_attr('sensor.entur_ringnotveien_platform_44778', 'route') }}"
      icon_template: mdi:bus

###############################
###          WEATHER        ###
###############################

- platform: yr
  monitored_conditions:
    - temperature
    - symbol
    - windSpeed
- platform: darksky
  api_key: !secret dark_sky_token
  language: nb
  forecast:
    - 0
  monitored_conditions:
    - summary
- platform: template
  sensors:
    air_quality_pm10:
      friendly_name: "Air quality pm10"
      unit_of_measurement: ug/m3
      value_template: "{{ state_attr('air_quality.air_quality_norway', 'particulate_matter_10') }}"
      icon_template: mdi:air-purifier

###############################
###            MISC         ###
###############################

# Denne burde hete noe annet...
- platform: template
  sensors:
    voltage_chili:
      friendly_name: "Spenning"
      unit_of_measurement: 'V'
      icon_template: mdi:flash
      value_template: "{{ state_attr('switch.bookshelf', 'voltage') }}"

    vaskemaskin_effekt:
      friendly_name: "Vaskemaskin effekt"
      unit_of_measurement: 'W'
      icon_template: mdi:washing-machine
      value_template: "{{ state_attr('switch.vaskemaskin', 'current_power_w') }}"

- platform: pi_hole
  host: !secret rpi_url

###############################
###         MI FLORA        ###
###############################
- platform: miflora
  mac: !secret miflora1_mac
  name: Miflora1
- platform: miflora
  mac: !secret miflora2_mac
  name: Miflora2
- platform: miflora
  mac: !secret miflora3_mac
  name: Miflora3
- platform: miflora
  mac: !secret miflora4_mac
  name: Miflora4
- platform: miflora
  mac: !secret miflora5_mac
  name: Miflora5
- platform: miflora
  mac: !secret miflora6_mac
  name: Miflora6
- platform: miflora
  mac: !secret miflora7_mac
  name: Miflora7
- platform: miflora
  mac: !secret miflora8_mac
  name: Miflora8
- platform: miflora
  mac: !secret miflora9_mac
  name: Miflora9
- platform: miflora
  mac: !secret miflora10_mac
  name: Miflora10
- platform: miflora
  mac: !secret miflora11_mac
  name: Miflora11
