###############################
###        SYSTEM           ###
###############################

- alias: "Startup Notification"
  trigger:
    - platform: homeassistant
      event: start
  action:
    - service: !secret notification1
      data:
        message: "Restarted"

###############################
###           CAR           ###
###############################

- alias: "Car battery notification"
  trigger:
    platform: time
    at: '21:30:00'
  condition:
    - condition: state
      entity_id: !secret car-external-power
      state: 'off'
    - condition: numeric_state
      entity_id: !secret car-battery
      below: 51
  action:
    - service: !secret notification1
      data:
        title: "Vurder å lade bilen."
        message: !secret car-battery-message

###############################
###        APPLIANCES       ###
###############################

#- alias: "Vaskemaskin ferdig"
#  trigger:
#    - platform: state
#      entity_id: binary_sensor.vaskemaskin
#      to: 'off'
#  action:
#    - service: !secret notification2
#      data:
#        message: "Vaskemaskinen er ferdig"

###############################
###          ZONES          ###
###############################

- alias: 'Fra barnehage'
  trigger:
    platform: zone
    entity_id: !secret dad_person
    zone: zone.barnehage
    event: leave
  condition:
    - condition: time
      weekday:
        - mon
        - tue
        - wed
        - thu
        - fri
    - condition: state
      entity_id: !secret device_tracker2
      state: home
  action:
    - service: !secret notification2
      data:
        message: "På vei hjem fra barnehagen"

###############################
###         PLANTS          ###
###############################

#- alias: 'Vanne draketre på kjøkkenet (26)'
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.miflora3_moisture
#    below: 15
#  action:
#    - service: !secret notification1
#      data_template:
#        message: >
#          {% if states('sensor.miflora3_conductivity') | int < 350 %}
#          Draketre på kjøkkenet (26) trenger vann og mye næring.
#          {% elif states('sensor.miflora3_conductivity') | int < 500 %}
#          Draketre på kjøkkenet (26) trenger vann og muligens noe næring.
#          {% else %}
#          Draketre på kjøkkenet (26) trenger vann uten næring.
#          {% endif %}
- alias: 'Vanne fiken oppe (27)'
  trigger:
    platform: numeric_state
    entity_id: sensor.miflora1_moisture
    below: 20
  action:
    - service: !secret notification1
      data_template:
        message: >
          {% if states('sensor.miflora1_conductivity') | int < 350 %}
          Fiken oppe (27) trenger vann og mye næring.
          {% elif states('sensor.miflora1_conductivity') | int < 500 %}
          Fiken oppe (27) trenger vann og muligens noe næring.
          {% else %}
          Fiken oppe (27) trenger vann uten næring.
          {% endif %}
- alias: 'Vanne fiken ved inngang (31)'
  trigger:
    platform: numeric_state
    entity_id: sensor.miflora2_moisture
    below: 20
  action:
    - service: !secret notification1
      data_template:
        message: >
          {% if states('sensor.miflora3_conductivity') | int < 350 %}
          Fiken ved inngang (28) trenger vann og mye næring.
          {% elif states('sensor.miflora3_conductivity') | int < 500 %}
          Fiken ved inngang (28) trenger vann og muligens noe næring.
          {% else %}
          Fiken ved inngang (28) trenger vann uten næring.
          {% endif %}
#- alias: 'Vanne Devils backbone i trappå (29)'
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.miflora5_moisture
#    below: 7
#  action:
#    - service: !secret notification1
#      data_template:
#        message: >
#          {% if states('sensor.miflora5_conductivity') | int < 50 %}
#          Devils backbone i trappå (29) trenger vann og mye næring.
#          {% elif states('sensor.miflora5_conductivity') | int < 150 %}
#          Devils backbone i trappå (29) trenger vann og muligens noe næring.
#          {% else %}
#          Devils backbone i trappå (29) trenger vann uten næring.
#          {% endif %}
- alias: 'Vanne Peter P. ute (72)'
  trigger:
    platform: numeric_state
    entity_id: sensor.miflora8_moisture
    below: 20
  action:
    - service: !secret notification1
      data_template:
        message: >
          {% if states('sensor.miflora8_conductivity') | int < 150 %}
          Peter P. ute (72) trenger vann og mye næring.
          {% elif states('sensor.miflora8_conductivity') | int < 300 %}
          Peter P. ute (72) trenger vann og muligens noe næring.
          {% else %}
          Peter P. ute (72) trenger vann uten næring.
          {% endif %}
#- alias: 'Vanne Arekapalme (105)'
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.miflora4_moisture
#    below: 15
#  action:
#    - service: !secret notification1
#      data_template:
#        message: >
#          {% if states('sensor.miflora4_conductivity') | int < 350 %}
#          Arekapalme (105) trenger vann og mye næring.
#          {% elif states('sensor.miflora4_conductivity') | int < 500 %}
#          Arekapalme (105) trenger vann og muligens noe næring.
#          {% else %}
#          Arekapalme (105) trenger vann uten næring.
#          {% endif %}
#- alias: 'Vanne Trachycarpus Fortunei (48)'
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.miflora6_moisture
#    below: 15
#  action:
#    - service: !secret notification1
#      data_template:
#        message: >
#          {% if states('sensor.miflora6_conductivity') | int < 350 %}
#          Fortunei-palmen på kjøkkenet (48) trenger vann og mye næring.
#          {% elif states('sensor.miflora6_conductivity') | int < 500 %}
#          Fortunei-palmen på kjøkkenet (48) trenger vann og muligens noe næring.
#          {% else %}
#          Fortunei-palmen på kjøkkenet (48) trenger vann uten næring.
#          {% endif %}
- alias: 'Vanne Cherry Bomb chili (75)'
  trigger:
    platform: numeric_state
    entity_id: sensor.miflora7_moisture
    below: 20
  action:
    - service: !secret notification1
      data_template:
        message: >
          {% if states('sensor.miflora7_conductivity') | int < 150 %}
          Cherry Bomb chili (75) trenger vann og mye næring.
          {% elif states('sensor.miflora7_conductivity') | int < 300 %}
          Cherry Bomb chili (75) trenger vann og muligens noe næring.
          {% else %}
          Cherry Bomb chili (75) trenger vann uten næring.
          {% endif %}
- alias: 'Vanne Aji Charapita (78)'
  trigger:
    platform: numeric_state
    entity_id: sensor.miflora9_moisture
    below: 22
  action:
    - service: !secret notification1
      data_template:
        message: >
          {% if states('sensor.miflora9_conductivity') | int < 200 %}
          Aji Charapita (78) trenger vann og mye næring.
          {% elif states('sensor.miflora9_conductivity') | int < 400 %}
          Aji Charapita (78) trenger vann og muligens noe næring.
          {% else %}
          Aji Charapita (78) trenger vann uten næring.
          {% endif %}
#- alias: 'Vanne Schefflera Arboricola (107)'
#  trigger:
#    platform: numeric_state
#    entity_id: sensor.miflora10_moisture
#    below: 15
#  action:
#    - service: !secret notification1
#      data_template:
#        message: >
#          {% if states('sensor.miflora10_conductivity') | int < 350 %}
#          Paraplypalmen (107) trenger vann og mye næring.
#          {% elif states('sensor.miflora10_conductivity') | int < 500 %}
#          Paraplypalmen (107) trenger vann og muligens noe næring.
#          {% else %}
#          Paraplypalmen (107) trenger vann uten næring.
#          {% endif %}
